framework:
    messenger:
        transports:
            messages_queue:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: messages
                        type: direct
                    queues:
                        messages: ~

        routing:
            App\Message\ChatMessage: messages_queue 