version: '3.8'

services:
  nginx:
    restart: unless-stopped
    environment:
      - NGINX_PORT=80
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro  # для SSL сертификатов

  app:
    restart: unless-stopped
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
      - MESSENGER_TRANSPORT_DSN=amqp://user:${RABBITMQ_PASSWORD}@rabbitmq:5672/%2f/messages
      - DOMAIN=${DOMAIN}
      - WEBSOCKET_URL=wss://${DOMAIN}/ws
      
  db-primary:
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - db_password

  websocket:
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  rabbitmq:
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS_FILE=/run/secrets/rabbitmq_password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
    secrets:
      - rabbitmq_password

secrets:
  db_password:
    file: ./secrets/db_password.txt
  rabbitmq_password:
    file: ./secrets/rabbitmq_password.txt

volumes:
  db_data:
  rabbitmq_data: 