api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    formats:
        json: [ 'application/json' ]
        mime_types: [ 'multipart/form-data' ]
    docs_formats:
        json: [ 'application/json' ]
        jsonopenapi: [ 'application/vnd.openapi+json' ]
        html: [ 'text/html' ]