lexik_jwt_authentication:
  token_ttl: 31536000
  user_id_claim: user_id
  secret_key: '%jwt_private_key%'
#  signature_key: '%jwt_private_key%'
  public_key: '%jwt_public_key%'
  encoder:
    signature_algorithm: HS256