framework:
    messenger:
        default_bus: command.bus
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus: ~

        failure_transport: failed

        transports:
            sync: 'sync://'
            failed: 'doctrine://default?queue_name=failed'
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: messages
                        type: direct
                    queues:
                        messages: ~
            # … остальные транспорты (sync, main_processing, notifications) …

        routing:
            '*': async
