framework:
    messenger:
        default_bus: command.bus
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus: ~

        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
            async_messages:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: messages
                        type: direct
                    queues:
                        messages: ~
            messages_queue:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: messages
                        type: direct
                    queues:
                        messages: ~

            sync: 'sync://'

            main_processing:
                dsn: '%env(MESSENGER_MAIN_DSN)%'
                options:
                    exchange:
                        name: main_processing
                        type: direct
                    queues:
                        main_processing_queue: ~

            notifications:
                dsn: '%env(MESSENGER_NOTIFICATIONS_DSN)%'
                options:
                    exchange:
                        name: notifications
                        type: direct
                    queues:
                        notifications_queue: ~

        routing:
            '*': async
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
#            App\Message\ProcessChatMessage: messages_queue
#            App\Message\ProcessChatMessage: async_messages
#            App\Message\NotificationMessage: messages_queue
#            App\Message\NotificationMessage: async_messages

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
